import os

__all__ = [
    "PASTEBIN_API_DEV_KEY",
    "PASTEBIN_USERNAME",
    "PASTEBIN_PASSWORD",
]

PASTEBIN_API_DEV_KEY = os.environ["PASTEBIN_API_DEV_KEY"]
PASTEBIN_USERNAME = os.environ["PASTEBIN_USERNAME"]
PASTEBIN_PASSWORD = os.environ["PASTEBIN_PASSWORD"]
